### PR TITLE
Drawio template for core domain charts

### PR DESCRIPTION
**Pull request by horsdal**
This is the drawio template mentionend in https://github.com/ddd-crew/core-domain-charts/issues/10

The template looks like this 
core-domain-chart-template

There are 2 layers in the drawio file. The chart itself include the colored areas (generic, supporting, and core) are the background and are locked. The rest is the foregorund (the red circles with text beside) and is supposed to be edited.

I am more than happy to tweak this based on feedback.

### CODE REVIEW

**Comment by NTCoding** [comment]
Nice work @horsdal.

I'm not familiar with draw.io so I imported the template and I could see the potential to do some interesting things with layers.

I think the template itself provides all the basic notation required to started. You could start adding all of the extra notation and team topologies icons, although there are benefits to keep it basic and allowing people to add their own notation as and when needed.

**Comment by horsdal** [comment]
Thanks for the feedback.
I will be away from my computer for the rest of the week. When I'm back I'll give it an iteration where I:

- Try to fix snapping issue
- Add the rest of the notation
- Add a how-to box to the drawing

**Comment by codeliner** [comment]
Nice work @horsdal . Good that I did not find the time last week to prepare my [PR](https://github.com/ddd-crew/core-domain-charts/issues/8#issuecomment-647184262). Now I can use your template :)

**Comment by codeliner** [comment]
@horsdal You can fix the snapping issue by adding the style `connectable=0` to the background shapes (Core, Supporting, Generic):
- unlock background layer
- select shape
- choose edit style from right panel

image

**Comment by horsdal** [comment]
Thanks for the tip @codeliner. I didn't know you could that 🙌

**Comment by codeliner** [comment]
@horsdal yeah, I think stuff like that is not documented, but I'm working with the underlying JS library of draw.io every day (our own product is based on the same lib), so I know one or two details about it :D

**Pull request merged**
