### PR TITLE
Adding notation and how-to to drawio template

### PR DESCRIPTION
**Pull request by horsdal**
Following up on this https://github.com/ddd-crew/core-domain-charts/pull/11#issuecomment-651602461 and adding the remaining notation to the drawio template and fixing the snapping issue (thanks @codeliner 🎉 )

The template now looks like this when opened in drawio:

core-domain-chart-template

### CODE REVIEW

**Comment by codeliner** [comment]
Nice!

I experimented with Core Domain Charts using the draw.io template. To improve readability, I applied some "fillOpacity" to the background shapes (Generic, Supporting, Core) to visually move them in the background. Maybe an Idea for the template?

**Comment by yellowbrickc** [comment]
@horsdal what do you think about the idea of @codeliner ? Would you include it in your PR or rather leave it as it is? The 3rd option is that @codeliner commits his improvements to this PR...
Thank you both anyway!

**Comment by horsdal** [comment]
Thanks for the feedback!
I set 60% fill opacity on the colored background shapes, and I agree it does indeed increase readability.

**Comment by yellowbrickc** [comment]
Let make it public available then :)

**Pull request merged**
